version: '3'

services:

  hlds:
    container_name: cs_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=27015
      - MAP=de_dust2
      - MAXPLAYERS=16
      - SV_LAN=0
    ports:
      - 27015:27015/udp
      - 27015:27015
    volumes:
      - ./config/banned.cfg:/hlds/cstrike/banned.cfg
      - ./config/listip.cfg:/hlds/cstrike/listip.cfg
      - ./config/server.cfg:/hlds/cstrike/server.cfg
      - ./config/mapcycle.txt:/hlds/cstrike/mapcycle.txt
